/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'stefan' at '21.01.17 08:22' with Gradle 3.1
 *
 * @author stefan, @date 21.01.17 08:22
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
